In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("D:\PythonProject\webformyself\price.csv", sep=';')
df

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Yevheniia\AppData\Local\Temp\ipykernel_8752\2719157614.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("D:\PythonProject\webformyself\price.csv", sep=';')

    id                                              title   price
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...     NaN
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000

In [5]:
df['price']

0     10.000
1        NaN
2      7.999
3     25.000
4     35.000
5      5.000
6     11.000
7     16.000
8     15.000
9        NaN
10    10.000
Name: price, dtype: float64

In [7]:
df[['title', 'price']]

                                                title   price
0   Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000
1   Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN
2   Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999
3   Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000
4   Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000
5   Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000
6   Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000
7   Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000
8   Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000
9   Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...     NaN
10  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000

In [9]:
df.at[0, 'price']

np.float64(10.0)

In [10]:
df['price'][0]

np.float64(10.0)

In [12]:
df.loc[0, 'price']

np.float64(10.0)

In [14]:
df.loc[1, :]

id                                                       2
title    Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...
price                                                  NaN
Name: 1, dtype: object

In [15]:
df.loc[1][['id', 'title']]

id                                                       2
title    Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...
Name: 1, dtype: object

In [17]:
df.loc[[0, 1, 2, 6]]

   id                                              title   price
0   1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000
1   2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN
2   3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999
6   7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000

In [23]:
df.loc[0:4, :]

   id                                              title   price
0   1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000
1   2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN
2   3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999
3   4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000
4   5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000

In [25]:
df.loc[:, ['price', 'id']]

     price  id
0   10.000   1
1      NaN   2
2    7.999   3
3   25.000   4
4   35.000   5
5    5.000   6
6   11.000   7
7   16.000   8
8   15.000   9
9      NaN  10
10  10.000  11

In [26]:
df.loc[:2, 'id': 'price']

   id                                              title   price
0   1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000
1   2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN
2   3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999

In [27]:
df.iloc[0:4, 1:2]

                                               title
0  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....
1  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...
2  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...
3  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...

ПОЛУЧИТЬ СТРОКИ С ЧЕТНЫМИ ИНДЕКСАМИ

In [32]:
df.loc[: : 2, :]

    id                                              title   price
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000

ПОЛУЧИТЬ СТРОКИ С НЕЧЕТНЫМИ ИНДЕКСАМИ

In [35]:
df.loc[1 :: 2, :]

   id                                              title  price
1   2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...    NaN
3   4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...   25.0
5   6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...    5.0
7   8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...   16.0
9  10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...    NaN

ПОЛУЧИТЬ "ПЕРЕВЕРНУТЫЙ ДАТАФРЕЙМ"

In [39]:
df.loc[ :: -1]

    id                                              title   price
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...     NaN
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000

ПОЛУЧИТЬ ВСЕ СТРОКИ С ИМЕЮЩЕЙСЯ ЦЕНОЙ

In [40]:
df.loc[df.price.notna()]

    id                                              title   price
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000

ПОЛУЧИТЬ ТОЛЬКО ПЕРВУЮ СТРОКУ

In [43]:
df.loc[0, :]

id                                                       1
title    Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....
price                                                 10.0
Name: 0, dtype: object

ПОЛУЧИТЬ ТОЛЬКО ПОСЛЕДНЮЮ СТРОКУ

In [53]:
df.iloc[ -1]

id                                                      11
title    Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...
price                                                 10.0
Name: 10, dtype: object

ПОЛУЧИТЬ ТОЛЬКО ПОСЛЕДНЮЮ КОЛОНКУ ИСПОЛЬЗУЯ СРЕЗЫ

In [54]:
df.iloc[:, -1]

0     10.000
1        NaN
2      7.999
3     25.000
4     35.000
5      5.000
6     11.000
7     16.000
8     15.000
9        NaN
10    10.000
Name: price, dtype: float64

ДОБАВЛЕНИЕ И УДАЛЕНИЕ СТОЛБЦОВ

In [56]:
df['qty'] = 2
df

    id                                              title   price  qty
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...     NaN    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2

In [57]:
df['test'] = df.id
df

    id                                              title   price  qty  test
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2     1
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN    2     2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2     3
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2     4
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2     5
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2     6
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2     7
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2     8
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2     9
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...     NaN    2    10
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2    11

In [58]:
df['total'] = df.price * df.qty
df

,id,title,price,qty,test,total
0,1,Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....,10.000,2,1,20.000
1,2,Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...,NaN,2,2,NaN
2,3,Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...,7.999,2,3,15.998
3,4,Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...,25.000,2,4,50.000
4,5,Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....,35.000,2,5,70.000
5,6,Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...,5.000,2,6,10.000
6,7,"Ноутбук Apple MacBook Air 13"" 256GB 2020 Space...",11.000,2,7,22.000
7,8,Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...,16.000,2,8,32.000
8,9,Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...,15.000,2,9,30.000
9,10,Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...,NaN,2,10,NaN
10,11,Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...,10.000,2,11,20.000

In [60]:
cities = pd.read_csv("D:\PythonProject\webformyself\city.csv", sep = ';')
cities

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Yevheniia\AppData\Local\Temp\ipykernel_8752\4203273695.py:1: SyntaxWarning: invalid escape sequence '\P'
  cities = pd.read_csv("D:\PythonProject\webformyself\city.csv", sep = ';')

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [61]:
cities['Location'] = cities.Name + ' ' + cities.CountryCode
cities

,ID,Name,CountryCode,District,Population,Location
0,1,Kabul,AFG,Kabol,1780000,Kabul AFG
1,2,Qandahar,AFG,Qandahar,237500,Qandahar AFG
2,3,Herat,AFG,Herat,186800,Herat AFG
3,4,Mazar-e-Sharif,AFG,Balkh,127800,Mazar-e-Sharif AFG
4,5,Amsterdam,NLD,Noord-Holland,731200,Amsterdam NLD
...,...,...,...,...,...,...
4074,4075,Khan Yunis,PSE,Khan Yunis,123175,Khan Yunis PSE
4075,4076,Hebron,PSE,Hebron,119401,Hebron PSE
4076,4077,Jabaliya,PSE,North Gaza,113901,Jabaliya PSE
4077,4078,Nablus,PSE,Nablus,100231,Nablus PSE
4078,4079,Rafah,PSE,Rafah,92020,Rafah PSE

In [62]:
df

,id,title,price,qty,test,total
0,1,Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....,10.000,2,1,20.000
1,2,Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...,NaN,2,2,NaN
2,3,Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...,7.999,2,3,15.998
3,4,Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...,25.000,2,4,50.000
4,5,Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....,35.000,2,5,70.000
5,6,Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...,5.000,2,6,10.000
6,7,"Ноутбук Apple MacBook Air 13"" 256GB 2020 Space...",11.000,2,7,22.000
7,8,Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...,16.000,2,8,32.000
8,9,Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...,15.000,2,9,30.000
9,10,Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...,NaN,2,10,NaN
10,11,Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...,10.000,2,11,20.000

In [64]:
# axis = 0 - для строкб axis= 1 - для столбцов
df.drop('test', axis=1)

    id                                              title   price  qty   total
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2  20.000
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN    2     NaN
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2  15.998
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2  50.000
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2  70.000
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2  10.000
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2  22.000
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2  32.000
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2  30.000
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...     NaN    2     NaN
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2  20.000

In [65]:
df

,id,title,price,qty,test,total
0,1,Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....,10.000,2,1,20.000
1,2,Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...,NaN,2,2,NaN
2,3,Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...,7.999,2,3,15.998
3,4,Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...,25.000,2,4,50.000
4,5,Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....,35.000,2,5,70.000
5,6,Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...,5.000,2,6,10.000
6,7,"Ноутбук Apple MacBook Air 13"" 256GB 2020 Space...",11.000,2,7,22.000
7,8,Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...,16.000,2,8,32.000
8,9,Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...,15.000,2,9,30.000
9,10,Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...,NaN,2,10,NaN
10,11,Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...,10.000,2,11,20.000

In [66]:
# df.drop(['test', 'total'], axis=1, inplace=True)   inplace=True - перезапись датафрейма
df.drop(columns=['test', 'total'], axis=1, inplace=True)
df

    id                                              title   price  qty
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...     NaN    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...     NaN    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2

In [68]:
df.drop([1, 9])

    id                                              title   price  qty
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2

In [69]:
df.price.isna()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
Name: price, dtype: bool

In [72]:
df.loc[df.price.isna(), :].index

Index([1, 9], dtype='int64')

In [73]:
df.drop(df.loc[df.price.isna(), :].index)

    id                                              title   price  qty
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2

In [74]:
df.dropna(subset=['price'])

    id                                              title   price  qty
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2

In [75]:
df.fillna(0)

    id                                              title   price  qty
0    1  Ноутбук Acer Aspire 5 A515-54G-502N (NX.HVGEU....  10.000    2
1    2  Ноутбук Asus ROG Strix G15 G512LI-HN057 (90NR0...   0.000    2
2    3  Ноутбук HP Pavilion Gaming 15-bc504ur (7DT87EA...   7.999    2
3    4  Ноутбук HP Pavilion Notebook 15-cw1011ua (8RW1...  25.000    2
4    5  Ноутбук Acer Aspire 7 A715-41G-R7MZ (NH.Q8LEU....  35.000    2
5    6  Ноутбук Dell Inspiron 3582 (I3582C54H5NIL-BK) ...   5.000    2
6    7  Ноутбук Apple MacBook Air 13" 256GB 2020 Space...  11.000    2
7    8  Ноутбук Asus ROG Strix G15 G512LI-HN094 (90NR0...  16.000    2
8    9  Ноутбук HP Pavilion Notebook 15-cw1002ua (7KE5...  15.000    2
9   10  Ноутбук HP Pavilion Notebook 15-cw1005ua (7ZF7...   0.000    2
10  11  Ноутбук Lenovo IdeaPad L340-15IRH Gaming (81LK...  10.000    2